"""Read EX16 joint angles and visualize the glove in Viser."""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import numpy as np
import viser
import yourdfpy
from viser.extras import ViserUrdf

PROJECT_ROOT = Path(__file__).resolve().parent
URDF_PATH = PROJECT_ROOT / "libgex" / "ex16" / "urdf" / "glove4.urdf"
MESH_DIR = PROJECT_ROOT / "libgex" / "ex16" / "meshes"
DEFAULT_STATE_ENDPOINT = "tcp://127.0.0.1:5567"
STATE_TOPIC = "ex16/state"
JOINT_COUNT = 16


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Subscribe to EX16 joint states and display them in Viser."
    )
    parser.add_argument("--state-endpoint", default=DEFAULT_STATE_ENDPOINT)
    parser.add_argument("--timeout-ms", type=int, default=2000)
    parser.add_argument("--host", default="0.0.0.0", help="Viser bind address")
    parser.add_argument("--port-viser", type=int, default=8080, help="Viser web port")
    return parser.parse_args()


def resolve_mesh(fname: str) -> str:
    """Resolve the package:// paths generated by SolidWorks."""
    return str(MESH_DIR / Path(fname).name)


def load_urdf() -> yourdfpy.URDF:
    return yourdfpy.URDF.load(
        URDF_PATH,
        build_scene_graph=True,
        load_meshes=True,
        build_collision_scene_graph=False,
        load_collision_meshes=False,
        filename_handler=resolve_mesh,
    )


def main() -> None:
    args = parse_args()
    if args.timeout_ms <= 0:
        raise ValueError("--timeout-ms must be greater than zero")
    try:
        import zmq
    except ImportError as exc:
        raise SystemExit("pyzmq is required: python -m pip install pyzmq") from exc

    urdf = load_urdf()
    expected_names = [f"joint{i}" for i in range(1, 17)]
    missing = set(expected_names) - set(urdf.actuated_joint_names)
    if missing:
        raise RuntimeError(f"EX16 URDF is missing joints: {sorted(missing)}")

    server = viser.ViserServer(host=args.host, port=args.port_viser)
    server.scene.set_up_direction("+z")

    # Frame the roughly 30 cm glove closely on a white Viser canvas.
    model_center = np.asarray(urdf.scene.bounds).mean(axis=0)
    model_size = float(np.linalg.norm(urdf.scene.extents))
    view_direction = np.asarray([1.0, -1.0, 0.7])
    view_direction /= np.linalg.norm(view_direction)
    server.initial_camera.look_at = tuple(float(value) for value in model_center)
    server.initial_camera.position = tuple(
        float(value)
        for value in model_center + view_direction * model_size * 1.15
    )
    server.initial_camera.up = (0.0, 0.0, 1.0)
    server.initial_camera.fov = np.deg2rad(50.0)

    viser_hand = ViserUrdf(server, urdf, root_node_name="/ex16")
    print(f"Viser is running at http://127.0.0.1:{args.port_viser}")

    context = zmq.Context.instance()
    subscriber = context.socket(zmq.SUB)
    subscriber.linger = 0
    subscriber.rcvtimeo = args.timeout_ms
    subscriber.setsockopt_string(zmq.SUBSCRIBE, STATE_TOPIC)
    subscriber.connect(args.state_endpoint)
    print(f"Subscribing to {args.state_endpoint}, topic={STATE_TOPIC}")

    last_print = 0.0
    try:
        while True:
            message = subscriber.recv_string()
            topic, encoded_payload = message.split(" ", 1)
            if topic != STATE_TOPIC:
                continue
            payload = json.loads(encoded_payload)
            joint_degrees = np.asarray(payload["urdf_deg"], dtype=np.float64)
            if joint_degrees.shape != (JOINT_COUNT,):
                raise ValueError(
                    f"Expected {JOINT_COUNT} joint values, got {joint_degrees.shape}"
                )
            joint_by_name = dict(zip(expected_names, np.deg2rad(joint_degrees)))
            configuration = np.array(
                [joint_by_name[name] for name in urdf.actuated_joint_names],
                dtype=np.float64,
            )
            viser_hand.update_cfg(configuration)

            # Print at 2 Hz so the terminal remains readable.
            now = time.monotonic()
            if now - last_print >= 0.5:
                print(np.round(joint_degrees, 2).tolist())
                last_print = now
    except KeyboardInterrupt:
        print("Stopping EX16 viewer...")
    except zmq.Again as exc:
        raise TimeoutError(
            f"No EX16 state received from {args.state_endpoint} within "
            f"{args.timeout_ms} ms; start nodes/ex16_zmq_node.py first"
        ) from exc
    finally:
        subscriber.close()


if __name__ == "__main__":
    main()
